name: oshiruco_app
description: oshiruco app development by flutter

publish_to: 'none'

version: 3.1.3+3010308

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3

  # for state management
  hooks_riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1 
  state_notifier: ^0.7.0
  json_serializable: ^6.5.3

  # for routing
  routemaster: ^0.9.5

  # for ui
  flutter_svg: ^0.22.0
  adaptive_dialog: ^1.0.1
  webview_flutter: ^2.0.9
  image_picker: ^0.8.3+2
  flutter_native_image: ^0.0.6+1
  flutter_linkify: ^5.0.2
  store_redirect: ^2.0.0
  carousel_slider: ^4.0.0
  video_player: ^2.1.14
  future_progress_dialog: ^0.2.0
  image_cropper: ^1.4.1
  image: ^3.1.3
  path: ^1.8.0
  path_provider: 2.0.4
  highlight_text: ^1.4.1
  linkify: ^4.1.0

  # for use environment variables
  flutter_dotenv: ^5.0.0

  # for get mobile initialize information
  device_info_plus: ^2.1.0
  package_info_plus: ^1.0.6
  devicelocale: ^0.4.1

  # for api client
  dio: ^4.0.6
  retry: ^3.1.0
  http: ^0.13.3

  # for aws
  simple_s3: ^0.3.2

  # for firebase
  firebase_core: ^2.1.0
  firebase_remote_config: ^3.0.2
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  firebase_crashlytics: ^3.0.2
  firebase_analytics: ^10.0.2
  firebase_messaging: ^14.0.2 
  firebase_dynamic_links: ^5.0.2

  # for storage
  flutter_secure_storage: ^5.0.0

  enum_to_string: ^2.0.1
  intl: ^0.17.0
  flutter_phoenix: ^1.0.0
  flutter_picker: ^2.0.2

  version: ^2.0.0

  in_app_purchase: ^3.0.7

  appsflyer_sdk: ^6.4.0+1
  app_tracking_transparency: ^2.0.2+1

  # for Url luncher
  url_launcher: 6.0.10

  tutorial_coach_mark: ^1.1.1
  permission_handler: ^10.2.0 

  import_sorter: ^4.6.0
  carrier_info: ^2.0.4

flutter_gen:
  integrations:
    flutter_svg: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed_annotation: ^2.2.0
  freezed: ^2.2.0
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.staging
    - .env.development
    - assets/icons/
    - assets/icons/tab/
    - assets/images/
    - assets/svgs/

flutter_icons:
  android: true
  ios: true
  # image_path: "assets/icons/ic_launcher_APP.png"

import_sorter:
  emojis: true
  comments: false
