// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_User _$_$_UserFromJson(Map<String, dynamic> json) {
  return _$_User(
    bodyType: json['bodyType'] as String? ?? '',
    isBlock: json['isBlock'] as bool? ?? false,
    relativeExpert: (json['relativeExpert'] as List<dynamic>?)
            ?.map((e) => RelativeExpert.fromJson(e as Map<String, dynamic>))
            .toList() ??
        [],
    livedPlace: json['livedPlace'] as String? ?? '',
    voicePaths: json['voicePaths'] as String? ?? '',
    moviePaths: json['moviePaths'] as String? ?? '',
    supporterCode: json['supporterCode'] as String? ?? '',
    sickness: json['sickness'] as String? ?? '',
    userID: json['userID'] as String? ?? '',
    uuid: json['uuid'] as String? ?? '',
    housemate: json['housemate'] as String? ?? '',
    liked: json['liked'] as int? ?? 0,
    points: json['points'] as int? ?? 0,
    wantMarried: json['wantMarried'] as String? ?? '',
    children: json['children'] as String? ?? '',
    howtoMeet: json['howtoMeet'] as String? ?? '',
    logged: json['logged'] as String? ?? '',
    prevLogged: json['prevLogged'] as String? ?? '',
    datingState: json['datingState'] as String? ?? '',
    model: json['model'] as String? ?? '',
    grandchild: json['grandchild'] as String? ?? '',
    height: json['height'] as int? ?? 0,
    likes: json['likes'] as int? ?? 0,
    alcohol: json['alcohol'] as String? ?? '',
    supporterName: json['supporterName'] as String? ?? '',
    relativeGroup: (json['relativeGroup'] as List<dynamic>?)
            ?.map((e) => RelativeGroup.fromJson(e as Map<String, dynamic>))
            .toList() ??
        [],
    gonePlace: json['gonePlace'] as String? ?? '',
    appVer: json['appVer'] as String? ?? '',
    created: json['created'] as String? ?? '',
    isSelfHistory: json['isSelfHistory'] as bool? ?? false,
    isLiked: json['isLiked'] as bool? ?? false,
    isFromLiked: json['isFromLiked'] as bool? ?? false,
    isMatching: json['isMatching'] as bool? ?? false,
    networkState: json['networkState'] as String? ?? '',
    livePlace: json['livePlace'] as String? ?? '',
    onlineSettings: json['onlineSettings'] as String? ?? '',
    cigarettes: json['cigarettes'] as String? ?? '',
    updated: json['updated'] as String? ?? '',
    activeness: json['activeness'] as int? ?? 0,
    photoPaths: json['photoPaths'] as String? ?? '',
    isFavorite: json['isFavorite'] as bool? ?? false,
    birthday: json['birthday'] as String? ?? '',
    gender: json['gender'] as String? ?? '',
    dateCost: json['dateCost'] as String? ?? '',
    bloodType: json['bloodType'] as String? ?? '',
    locale: json['locale'] as String? ?? '',
    house: json['house'] as String? ?? '',
    holiday: json['holiday'] as String? ?? '',
    osVer: json['osVer'] as String? ?? '',
    birthPlace: json['birthPlace'] as String? ?? '',
    hair: json['hair'] as String? ?? '',
    personality: json['personality'] as String? ?? '',
    walking: json['walking'] as String? ?? '',
    marriage: json['marriage'] as String? ?? '',
    nickname: json['nickname'] as String? ?? '',
    introduction: json['introduction'] as String? ?? '',
    historySettings: json['historySettings'] as String? ?? '',
    registState: json['registState'] as String? ?? '',
    address: json['address'] as String? ?? '',
    os: json['os'] as String? ?? '',
    tweet: json['tweet'] as String? ?? '',
    deviceID: json['deviceID'] as String? ?? '',
    religion: json['religion'] as String? ?? '',
    sociability: json['sociability'] as String? ?? '',
    carrier: json['carrier'] as String? ?? '',
    broAndSis: json['broAndSis'] as String? ?? '',
    houseKeeping: json['houseKeeping'] as String? ?? '',
    asset: json['asset'] as String? ?? '',
    age: json['age'] as int? ?? 0,
    account: json['account'] as String? ?? '',
    onlineState: json['onlineState'] as String? ?? '',
  );
}

Map<String, dynamic> _$_$_UserToJson(_$_User instance) => <String, dynamic>{
      'bodyType': instance.bodyType,
      'isBlock': instance.isBlock,
      'relativeExpert': instance.relativeExpert,
      'livedPlace': instance.livedPlace,
      'voicePaths': instance.voicePaths,
      'moviePaths': instance.moviePaths,
      'supporterCode': instance.supporterCode,
      'sickness': instance.sickness,
      'userID': instance.userID,
      'uuid': instance.uuid,
      'housemate': instance.housemate,
      'liked': instance.liked,
      'points': instance.points,
      'wantMarried': instance.wantMarried,
      'children': instance.children,
      'howtoMeet': instance.howtoMeet,
      'logged': instance.logged,
      'prevLogged': instance.prevLogged,
      'datingState': instance.datingState,
      'model': instance.model,
      'grandchild': instance.grandchild,
      'height': instance.height,
      'likes': instance.likes,
      'alcohol': instance.alcohol,
      'supporterName': instance.supporterName,
      'relativeGroup': instance.relativeGroup,
      'gonePlace': instance.gonePlace,
      'appVer': instance.appVer,
      'created': instance.created,
      'isSelfHistory': instance.isSelfHistory,
      'isLiked': instance.isLiked,
      'isFromLiked': instance.isFromLiked,
      'isMatching': instance.isMatching,
      'networkState': instance.networkState,
      'livePlace': instance.livePlace,
      'onlineSettings': instance.onlineSettings,
      'cigarettes': instance.cigarettes,
      'updated': instance.updated,
      'activeness': instance.activeness,
      'photoPaths': instance.photoPaths,
      'isFavorite': instance.isFavorite,
      'birthday': instance.birthday,
      'gender': instance.gender,
      'dateCost': instance.dateCost,
      'bloodType': instance.bloodType,
      'locale': instance.locale,
      'house': instance.house,
      'holiday': instance.holiday,
      'osVer': instance.osVer,
      'birthPlace': instance.birthPlace,
      'hair': instance.hair,
      'personality': instance.personality,
      'walking': instance.walking,
      'marriage': instance.marriage,
      'nickname': instance.nickname,
      'introduction': instance.introduction,
      'historySettings': instance.historySettings,
      'registState': instance.registState,
      'address': instance.address,
      'os': instance.os,
      'tweet': instance.tweet,
      'deviceID': instance.deviceID,
      'religion': instance.religion,
      'sociability': instance.sociability,
      'carrier': instance.carrier,
      'broAndSis': instance.broAndSis,
      'houseKeeping': instance.houseKeeping,
      'asset': instance.asset,
      'age': instance.age,
      'account': instance.account,
      'onlineState': instance.onlineState,
    };
